SELECT FUN.DATADM, FUN.NUMCAD, FUN.NOMFUN AS NOME, FUN.NUMCPF, FOL.CODEVE, FOL.DESEVE, FOL.TIPEVE,
       FOL.REFEVE AS "REFERÊNCIA", FOL.VALEVE AS VLRREAL, FOL.VAL AS VLRIMP, FOL.TIPCAL, FOL.PERREF,
       FUN.CODAGE, FUN.CONBAN, FUN.DIGBAN, CCU.NOMCCU as LOCAL, CAR.TITCAR as CARGO,
       FOL.VALSAL "SALBASE",
       FOL.BASEINSS, case when FOL.BASEIR = 0 then FOL.BASEINSS else FOL.BASEIR end AS BASEIR, FOL.faixaIR
 FROM (
 SELECT VRS.NUMCAD, VRS.CODEVE, EVC.DESEVE, EVC.TIPEVE, 
        VRS.REFEVE,
        VRS.VALEVE AS VAL, 
        VRS.VALEVE * 
        CASE EVC.TIPEVE 
          WHEN 1 THEN 1 
          WHEN 2 THEN 1 
          WHEN 3 THEN -1 
          WHEN 4 THEN 0
          WHEN 5 THEN 0
          WHEN 6 THEN 0
        END AS VALEVE, CAL.TIPCAL, CAL.PERREF, INF.BASINS AS BASEINSS, NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) AS BASEIR,
        case when NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) <= 2428.8 then 0 
             when NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) > 2428.8 and NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) <= 2826.65 then 7.5
             when NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) > 2826.65 and NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) <= 3751.05 then 15
             when NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) > 3751.05 and NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) <= 4664.68 then 22.5
             when NVL(IRF.BASCAL,0) + NVL(IRF.DEDSIM,0) > 4664.68 then 27.5
        end as faixaIR,
        SAL.VALSAL
   FROM VETORH.R046VER VRS 
   JOIN VETORH.R044CAL CAL ON (CAL.CODCAL = VRS.CODCAL) AND (CAL.NUMEMP = VRS.NUMEMP)
   JOIN VETORH.R008EVC EVC ON (EVC.CODTAB = VRS.TABEVE) AND (EVC.CODEVE = VRS.CODEVE)
   LEFT JOIN VETORH.R046INF INF ON (INF.NUMEMP = VRS.NUMEMP) AND (INF.NUMCAD = VRS.NUMCAD) AND (INF.CODCAL = VRS.CODCAL)
   LEFT JOIN VETORH.R046IRF IRF ON (IRF.NUMEMP = VRS.NUMEMP) AND (IRF.NUMCAD = VRS.NUMCAD) AND (IRF.TIPCOL = VRS.TIPCOL) AND (IRF.CODCAL = VRS.CODCAL)
   LEFT JOIN (SELECT HSA.NUMEMP, HSA.NUMCAD, HSA.VALSAL FROM VETORH.R038HSA HSA
               WHERE HSA.DATALT = (SELECT MAX(AX.DATALT) FROM VETORH.R038HSA AX WHERE AX.NUMEMP = HSA.NUMEMP AND AX.NUMCAD = HSA.NUMCAD AND AX.DATALT <= '01/06/2025')
                 AND HSA.SEQALT = (SELECT MAX(AX.SEQALT) FROM VETORH.R038HSA AX WHERE AX.NUMEMP = HSA.NUMEMP AND AX.NUMCAD = HSA.NUMCAD AND AX.DATALT = HSA.DATALT)
                  ) SAL   
          ON (SAL.NUMEMP = VRS.NUMEMP) AND (SAL.NUMCAD = VRS.NUMCAD)
  WHERE CAL.PERREF >= '01/06/2025'
    AND VRS.NUMEMP = 11
    AND CAL.TIPCAL in (11,91,31,32)
    AND VRS.NUMCAD = 175
    AND CAL.TIPCAL = 11
 )  FOL 
   JOIN VETORH.R034FUN FUN ON (FUN.NUMCAD = FOL.NUMCAD) AND (FUN.NUMEMP = 11)
                          AND (FUN.TIPCOL = 1) AND FUN.NUMCAD NOT IN (211,212)
   LEFT JOIN (SELECT HCC.NUMEMP, HCC.NUMCAD, HCC.CODCCU FROM VETORH.R038HCC HCC
              WHERE HCC.DATALT = (SELECT MAX(MX.DATALT) 
                                    FROM VETORH.R038HCC MX 
                                   WHERE MX.NUMEMP = HCC.NUMEMP 
                                     AND MX.NUMCAD = HCC.NUMCAD)) HCU ON (HCU.NUMEMP = FUN.NUMEMP) AND (HCU.NUMCAD = FUN.NUMCAD)                       
   LEFT JOIN VETORH.R018CCU CCU ON (CCU.NUMEMP = FUN.NUMEMP AND CCU.CODCCU = HCU.CODCCU)               
   LEFT JOIN VETORH.R024CAR CAR ON (CAR.CODCAR = FUN.CODCAR)
 order by nomfun, CODEVE